version: "3"

services:
  redis:
    image: "redis:latest"
    user: "1000:1000"
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - "redis:/data"
    command: redis-server --requirepass password
    restart: always

volumes:
  redis:
